### ISSUE TITLE
Could Addons be accessed from github.com directly ?

### ISSUE THREAD

**Issue by alvinwongcsh** [hexya-erp/docker#2]
Accessing Google and golang.org is prohibited in my place .

So could it be changed to avoid downloading problem such as the following when I run the Hexya docker :

go: github.com/hexya-addons/account@v0.0.41: Get https://proxy.golang.org/github.com/hexya-addons/account/@v/v0.0.41.mod: dial tcp 216.58.200.49:443: i/o timeout

Thanks .

**Comment by npiganeau** [comment]
That's an issue with setting of go modules proxy on your computer.

Maybe you could check https://goproxy.cn/
